### ISSUE TITLE
On intial screen, starting a Spades match actually starts a Hearts match

### ISSUE THREAD

**Issue by pirsonn** [dozingcat/CardsWithCats#4]
Hi,

First of all, great app and nice job! I'm playing with it a lot. So, thanks.

I noticed a small bug on the start screen, when no game is currently ongoing: clicking on "New Spades Match" actually starts a new Hearts match. Seems to be in file lib/main.dart:285.
I'm using V1.0.0 on Android 11 and got the app on F-Droid.

Current workaround: once in Hearts match, clicking on the menu > "New spades match" launches a real spades match this time.

**Comment by dozingcat** [comment]
Whoops, thanks for spotting this! Will be fixed in the next release.
