### ISSUE TITLE
Main menu "New spades match" button doesn't work

### ISSUE THREAD

**Issue by novellus** [dozingcat/CardsWithCats#8]
The "New spades match" button only works correctly if there is already a Hearts or Spades match in progress, otherwise it launches a Hearts match instead.

Reproduction steps:
* open app
* finish ongoing match (if there is one)
* from the main menu, select "New spades match"
* game launches Hearts match instead

Work around:
* after launching a hearts match, go to menu
* select "New spades match"
* game correctly launches Spades match this time

**Comment by dozingcat** [comment]
This has been fixed in https://github.com/dozingcat/CardsWithCats/pull/5. I hope to have a new release soon that will include it.
